//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int Id { get; set; }
        public System.DateTime Loan_date { get; set; }
        public System.DateTime Return_date { get; set; }
        public Nullable<System.DateTime> Returned_date { get; set; }
        public int Id_user { get; set; }
        public int Id_book { get; set; }
        public int Id_admin { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
